name: CD - Build Docker Images (Demo)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  # Build Docker Images (without pushing to registry)
  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build Auth Service Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend/auth-service
        push: false
        tags: movie-auth-service:latest
        
    - name: Build Comment Service Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend/comment-service
        push: false
        tags: movie-comment-service:latest
        
    - name: Build API Gateway Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend/api-gateway
        push: false
        tags: movie-api-gateway:latest
        
    - name: Build Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: false
        tags: movie-frontend:latest
        
    - name: Summary
      run: |
        echo "✅ All Docker images built successfully!"
        echo "📦 Images built:"
        echo "  - movie-auth-service:latest"
        echo "  - movie-comment-service:latest"
        echo "  - movie-api-gateway:latest"
        echo "  - movie-frontend:latest"
        echo ""
        echo "ℹ️  Note: Images are not pushed to registry (demo mode)"
